In [1]:
from neko.core.network import Network
from neko._visual.visualize_network import NetworkVisualizer
from neko._inputs.resources import Resources
from neko._annotations.gene_ontology import Ontology
import omnipath as op
import pandas as pd

First set the folder for input and output

In [2]:
data_folder = "../../data/"

figures_folder = "../../Figures/"

sif_output = "../../sif_files/"

Selecting as resources just Signor

In [3]:
resources = Resources()

In [4]:
resources.import_signor_tsv(data_folder + "signor_db.tsv")

Loading the data from Antoine

In [5]:
data = pd.read_csv(data_folder + "discrete_data.csv")

In [6]:
data.fillna("", inplace=True)
data.reset_index(drop=True, inplace=True)

In [7]:
data

,WNT,SHH,Group 3,Group 4,WNT and Group 3,SHH and Group 3,Group 3 and Group 4,WNT and Group 3 and Group 4,WNT and SHH and Group 3 and Group 4
0,CSNK2B,DMRTA1,GABRA5,POU2F1,SMARCA4,TGFBR1,CHD7,LHX2,ZIC1
1,LEF1,BCOR,IMPG2,LHX1,,,KDM5A,,ZIC4
2,TP53,SMO,ANPRC,SIX2,,,KDM4C,,
3,PAX3,NHLH1,RARX2,LHX5,,,ZMYM3,,
4,HOXDB13,YAP1,MYC,ZNF35,,,EZH2,,
5,CTNNB1,LDB1,CRX,BARHL1,,,KDM6A,,
6,NKD2,PCNT,LIN28B,MLL3,,,KDM1A,,
7,NKD1,NFATC1,GBRA5,STAT5A,,,KDM3A,,
8,ONECUT2,SOX13,SMAD9,UNCX,,,KDM7A,,
9,EMX2,SUFU,LHX9,MYCN,,,KDM5B,,
10,MAF,ATOH1,ATP10A,ARID5B,,,,,
11,MSX2,PTCH1,IRX8,EN2,,,,,
12,LET7,CEBPA,HLX,SIX6,,,,,
13,DDX3X,INSM1,GABRA3,ERK,,,,,
14,TENA,GLI2,,TBR1,,,,,
15,DMRT2,NCOR2,,OTX2,,,,,
16,RUNX2,RARB,,HLF,,,,,
17,HOXDB,PDLI3,,CUX2,,,,,
18,,SOX2,,ZNF513,,,,,
19,,POU3F3,,LMX1A,,,,,
20,,PBX1,,AKT,,,,,
21,,TCF12,,SNCAIP,,,,,
22,,BBX,,UNC5D,,,,,
23,,,,EOMES,,,,,
24,,,,KHDR2,,,,,
25,,,,EOMES/TBR2,,,,,

Selecting just Group 4 group

In [8]:
group4_list = set()

for column in data.columns:
    if "Group 4" in column: 
        group4_list = group4_list.union(set(data[column].replace({"":None}).dropna()))   

print(group4_list)

{'LMX1A', 'KDM5A', 'ZNF35', 'KDM4C', 'CHD7', 'UNC5D', 'EOMES', 'HLF', 'ZIC1', 'CUX2', 'LHX2', 'EOMES/TBR2', 'AKT', 'OTX2', 'MLL3', 'POU2F1', 'KDM7A', 'KDM6A', 'KDM3A', 'KDM1A', 'KDM5B', 'LHX5', 'STAT5A', 'KHDR2', 'SIX2', 'ZNF513', 'UNCX', 'ZMYM3', 'EZH2', 'ZIC4', 'SIX6', 'EN2', 'ERK', 'LHX1', 'MYCN', 'SNCAIP', 'TBR1', 'BARHL1', 'ARID5B'}

# Creating a Network starting from All Omnipath interactions

In [19]:
group4_net = Network(group4_list, resources = resources.interactions)

Error: node ZNF35 is not present in the resources database
Error: node EOMES/TBR2 is not present in the resources database
Error: node LHX5 is not present in the resources database
Error: node KHDR2 is not present in the resources database
Error: node SIX2 is not present in the resources database
Error: node ZNF513 is not present in the resources database
Error: node UNCX is not present in the resources database
Error: node ZMYM3 is not present in the resources database
Error: node ZIC4 is not present in the resources database
Error: node BARHL1 is not present in the resources database

In [20]:
group4_net.add_node("TBR2")

Adding the node that were not found manually: HOXDB13 --> HOXD13, HOXDB --> HOXD9, Q8N9L1 --> ZIC4

In [21]:
group4_net.nodes

   Genesymbol Uniprot Type
0       LMX1A  Q8TE12  NaN
1       KDM5A  P29375  NaN
2       KDM4C  Q9H3R0  NaN
3        CHD7  Q9P2D1  NaN
4       UNC5D  Q6UXZ4  NaN
5       EOMES  O95936  NaN
6         HLF  Q16534  NaN
7        ZIC1  Q15915  NaN
8        CUX2  O14529  NaN
9        LHX2  P50458  NaN
10       AKT1  P31749  NaN
11       OTX2  P32243  NaN
12      KMT2C  Q8NEZ4  NaN
13     POU2F1  P14859  NaN
14      KDM7A  Q6ZMT4  NaN
15      KDM6A  O15550  NaN
16      KDM3A  Q9Y4C1  NaN
17      KDM1A  O60341  NaN
18      KDM5B  Q9UGL1  NaN
19     STAT5A  P42229  NaN
20       EZH2  Q15910  NaN
21       SIX6  O95475  NaN
22        EN2  P19622  NaN
23      EPHB2  P29323  NaN
24       LHX1  P48742  NaN
25       MYCN  P04198  NaN
26     SNCAIP  Q9Y6H5  NaN
27       TBR1  Q16650  NaN
28     ARID5B  Q14865  NaN

In [ ]:
group4_net.complete_connection(maxlen=4, algorithm="dfs", only_signed=True, connect_with_bias=False, consensus=False)

In [ ]:
group4_net.nodes

In [ ]:
group4_net.edges

In [ ]:
group4_visualizer = NetworkVisualizer(group4_net,color_by='effect', noi=True)
output = figures_folder + "Group4/Group4_signor"
group4_visualizer.render(output_file=output)

# Exporting Network in sif file

In [16]:
from neko._outputs.exports import Exports

In [20]:
group4_net.remove_node("CUX2")

In [21]:
export = Exports(group4_net)

In [22]:
export.export_sif(sif_output + "Group4_signor.sif")