In [1]:
from neko.core.network import Network
from neko._visual.visualize_network import NetworkVisualizer
from neko._inputs.resources import Resources
from neko._annotations.gene_ontology import Ontology
import omnipath as op
import pandas as pd

First set the folder for input and output

In [2]:
data_folder = "../../data/"

figures_folder = "../../Figures/"

sif_output = "../../sif_files/"

Selecting as resources just Signor

In [3]:
resources = Resources()

In [4]:
resources.import_signor_tsv(data_folder + "signor_db.tsv")

Loading the data from Antoine

In [5]:
data = pd.read_csv(data_folder + "discrete_data.csv")

In [6]:
data.fillna("", inplace=True)
data.reset_index(drop=True, inplace=True)

In [7]:
data

,WNT,SHH,Group 3,Group 4,WNT and Group 3,SHH and Group 3,Group 3 and Group 4,WNT and Group 3 and Group 4,WNT and SHH and Group 3 and Group 4
0,CSNK2B,DMRTA1,GABRA5,POU2F1,SMARCA4,TGFBR1,CHD7,LHX2,ZIC1
1,LEF1,BCOR,IMPG2,LHX1,,,KDM5A,,ZIC4
2,TP53,SMO,ANPRC,SIX2,,,KDM4C,,
3,PAX3,NHLH1,RARX2,LHX5,,,ZMYM3,,
4,HOXDB13,YAP1,MYC,ZNF35,,,EZH2,,
5,CTNNB1,LDB1,CRX,BARHL1,,,KDM6A,,
6,NKD2,PCNT,LIN28B,MLL3,,,KDM1A,,
7,NKD1,NFATC1,GBRA5,STAT5A,,,KDM3A,,
8,ONECUT2,SOX13,SMAD9,UNCX,,,KDM7A,,
9,EMX2,SUFU,LHX9,MYCN,,,KDM5B,,
10,MAF,ATOH1,ATP10A,ARID5B,,,,,
11,MSX2,PTCH1,IRX8,EN2,,,,,
12,LET7,CEBPA,HLX,SIX6,,,,,
13,DDX3X,INSM1,GABRA3,ERK,,,,,
14,TENA,GLI2,,TBR1,,,,,
15,DMRT2,NCOR2,,OTX2,,,,,
16,RUNX2,RARB,,HLF,,,,,
17,HOXDB,PDLI3,,CUX2,,,,,
18,,SOX2,,ZNF513,,,,,
19,,POU3F3,,LMX1A,,,,,
20,,PBX1,,AKT,,,,,
21,,TCF12,,SNCAIP,,,,,
22,,BBX,,UNC5D,,,,,
23,,,,EOMES,,,,,
24,,,,KHDR2,,,,,
25,,,,EOMES/TBR2,,,,,

Selecting just Group 3 group

In [19]:
group3_list = set()

for column in data.columns:
    if "Group 3" in column: 
        group3_list = group3_list.union(set(data[column].replace({"":None}).dropna()))   

print(group3_list)

{'SMAD9', 'GBRA5', 'KDM6A', 'GABRA3', 'TGFBR1', 'KDM1A', 'IRX8', 'HLX', 'KDM5A', 'KDM7A', 'GABRA5', 'CHD7', 'ZIC4', 'LHX9', 'RARX2', 'LHX2', 'KDM3A', 'ANPRC', 'EZH2', 'KDM5B', 'LIN28B', 'KDM4C', 'ZIC1', 'SMARCA4', 'IMPG2', 'ZMYM3', 'MYC', 'ATP10A', 'CRX'}

# Creating a Network starting from All Omnipath interactions

In [25]:
group3_net = Network(group3_list, resources = resources.interactions)

Error: node GBRA5 is not present in the resources database
Error: node IRX8 is not present in the resources database
Error: node ZIC4 is not present in the resources database
Error: node LHX9 is not present in the resources database
Error: node RARX2 is not present in the resources database
Error: node ANPRC is not present in the resources database
Error: node IMPG2 is not present in the resources database
Error: node ZMYM3 is not present in the resources database
Error: node ATP10A is not present in the resources database

Adding the node that were not found manually: HOXDB13 --> HOXD13, HOXDB --> HOXD9, Q8N9L1 --> ZIC4

In [26]:
group3_net.add_node("GABRA5")

In [27]:
group3_net.nodes

   Genesymbol Uniprot Type
0       SMAD9  O15198  NaN
1       KDM6A  O15550  NaN
2      GABRA3  P34903  NaN
3      TGFBR1  P36897  NaN
4       KDM1A  O60341  NaN
5         HLX  Q14774  NaN
6       KDM5A  P29375  NaN
7       KDM7A  Q6ZMT4  NaN
8      GABRA5  P31644  NaN
9        CHD7  Q9P2D1  NaN
10       LHX2  P50458  NaN
11      KDM3A  Q9Y4C1  NaN
12       EZH2  Q15910  NaN
13      KDM5B  Q9UGL1  NaN
14     LIN28B  Q6ZN17  NaN
15      KDM4C  Q9H3R0  NaN
16       ZIC1  Q15915  NaN
17    SMARCA4  P51532  NaN
18        MYC  P01106  NaN
19        CRX  O43186  NaN

In [ ]:
group3_net.complete_connection(maxlen=4, algorithm="dfs", only_signed=True, connect_with_bias=False, consensus=False)

In [ ]:
group3_net.nodes

In [ ]:
group3_net.edges

In [ ]:
group3_visualizer = NetworkVisualizer(group3_net,color_by='effect', noi=True)
output = figures_folder + "Group3/Group3_signor"
group3_visualizer.render(output_file=output)

# Exporting Network in sif file

In [16]:
from neko._outputs.exports import Exports

In [17]:
export = Exports(group3_net)

In [18]:
export.export_sif(sif_output + "group3_signor.sif")

In [20]:
df = resources.interactions

In [21]:
df[df["source"] == "SIGNOR-C143"]

,source,target,is_directed,is_stimulation,is_inhibition,form_complex,consensus_direction,consensus_stimulation,consensus_inhibition,curation_effort,references,sources
25460,SIGNOR-C143,P35222,True,False,True,False,False,False,False,llicata,17208333,SIGNOR-250647
25461,SIGNOR-C143,P49815,True,True,False,False,True,True,False,miannu,32294430,SIGNOR-274101; SIGNOR-274102
25462,SIGNOR-C143,Q9GZM8,True,True,False,False,False,False,False,llicata,12796778,SIGNOR-250652
25463,SIGNOR-C143,SIGNOR-PH219,False,True,False,False,False,False,False,lperfetto,12640120,SIGNOR-273192